### ISSUE TITLE
mksquashfs FATAL ERROR:xz uncompress failed with error code 9 (fragment block error)

### ISSUE THREAD

**Issue by wonghang** [plougher/squashfs-tools#103]
Hi, just a bug report.

I was building a large squashfs, after running for a long time, I got the following error:

```
$ mksquashfs /somedirectory foobar.sqfs -progress -comp xz -b 1M -no-xattrs
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on foobar.sqfs, block size 1048576.
[========================================================================================================================================\     ] 3818344/3938057  96%
FATAL ERROR:xz uncompress failed with error code 9
```

I checked the code. I believe it is related to fragments:

https://github.com/plougher/squashfs-tools/blob/e595864642cd6fdaa22ef24a81b8fc26ffc00845/squashfs-tools/mksquashfs.c#L1438

and error code 9 means `LZMA_DATA_ERROR`

https://github.com/kobolabs/liblzma/blob/87b7682ce4b1c849504e2b3641cebaad62aaef87/src/liblzma/api/lzma/base.h#L172

I cannot hand you the data. I understand it is difficult to debug without the data. Sorry.

I am using the squashfs-tools on ubuntu 20.04.1 LTS

``` 
$ dpkg -l | grep squashfs
ii  squashfs-tools                             1:4.4-1                             amd64        Tool to create and append to squashfs filesystems
```

**Comment by plougher** [comment]
Thank you for the bug report, but, without any evidence that this is reproducible, there is no way of knowing whether this is a bug in Mksquashfs, or a problem elsewhere.

As you have discovered, a decompression failure in Mksquashfs relates to the failure to to decompress a fragment.  Fragments in Mksquashfs are compressed and written to disk, but are also cached in memory, in case they may be needed later for duplicate checking.  The more memory your system has, the larger amount of fragments are cached in memory.

If you get a decompression failure is it due to that compressed data going "bad".  Now there are numerous reasons why that might be, a program bug or a random bit-flip or corruption elsewhere.

I have received no other bug reports regarding this issue, and this is in code which has been stable for many years.   If there was a bug here that is a somewhat unlikely event.

Without anymore information, my inclination is to consider this failure not caused by a bug in Mksquashfs.
