### ISSUE TITLE
Cannot mount diskimage inside squash archive.

### ISSUE THREAD

**Issue by circuitikzuser** [plougher/squashfs-tools#104]
I know this must be a trivial question, but scouring manpage and the web I cannot get results.

Is it at all possible to mount a created disk  image inside a squash archive ?
I failed to do it.

As root user

I create a squash file system of the diskimage called 
`devsda1.img.sqsh`

I create two empty directories 
```
/mount1
/mount2
```

I mount devsda1.img.sqsh
`# mount devsda1.img.sqsh  /mount1`
I tried also with "-t squashfs" option but it mounts the same both ways and makes no difference to result below.
then cd'ing to /mount1 I can see the original image before compression namely devsda1.img

However when I try to mount the original image inside the squash mount, I get the following error.

```
# cd /mount1
# mount devsda1.img /mount2
mount: /mount2: cannot mount /dev/loop1 read-only.

```
I obviously tried with -o loop too, no change.

Surely I must be misunderstanding something as the failure to mount the image is the sole benefit of squashfs over archives like gzip and others only, since you dont have to extract before being able to mount the image inside the squash archive.

So what do I do wrong ?

**Comment by circuitikzuser** [comment]
I managed to solve it by brute force and pure luck, but I have no clue why this happened.

using  the following it now mounts. 
`#mount -o ro,norecovery,loop  devsda1.img /mount2`

Anyone can explain this to me as my backups need to have integrity  idf I use squashfs and so far it seems to be very "iffy"
Did squashfs somehow muck up the allocation tables ?

Is squashfs actually reliable enough for backups ?

**Comment by plougher** [comment]
You show a very bad attitude, asking for advice and in the same breath bad mouth and criticise the system you're trying to get help for. 

The problem is *you* and your lack of understanding.  I'll go through it nice and slowly.

1.  Your diskimage is a READ-WRITE filesystem.
2.  Squashfs is a READ-ONLY filesystem.

So when you do

<pre>
# cd /mount1
# mount devsda1.img /mount2
mount: /mount2: cannot mount /dev/loop1 read-only.
</pre>

The mount command will try to mount your filesystem READ-WRITE.  But, it can't because it is READ-ONLY.

*You* have to tell the system to mount the filesystem READ-ONLY then it will be happy.

Thanks for the great things you said about Squashfs BTW.  People like you make it all worth it ....

**Comment by circuitikzuser** [comment]
Show me exactly where I insulted your little ego.

**Comment by plougher** [comment]
Just FUCK OFF

**Comment by circuitikzuser** [comment]
Unfortunately I dont do that. 

So where did I insult your little ego ?
Just show me the particular issue so i can correct it  for you.
