### ISSUE TITLE
Unsupported filesystem version (Squashfs 4.0)

### ISSUE THREAD

**Issue by BreakfastSerial** [plougher/squashfs-tools#108]
I'm trying to unsquash a filesystem.image from a router (https://en.avm.de/fritz-lab/fresh-from-development/fresh-from-development/ FRITZ!Box 6490 Cable), I can upload the image somewhere if necessary.

```
$ unsquashfs -v              
unsquashfs version 4.4 (2019/08/29)

$ unsquashfs filesystem.image                                                                                                                        
Reading a different endian SQUASHFS filesystem on filesystem.image
Filesystem on filesystem.image is (4:0), which is a later filesystem version than I support!

$ file filesystem.image                                                                                                                            
filesystem.image: Squashfs filesystem, big endian, version 4.0, xz compressed, 5960480 bytes, 1104 inodes, blocksize: 65536 bytes, created: Tue Mar 10 23:41:20 1970

$ uname -a                                                                                                                                           
Linux kali 5.10.0-kali3-amd64 #1 SMP Debian 5.10.13-1kali1 (2021-02-08) x86_64 GNU/Linux
```

**Comment by AgentD** [comment]
Hi @BreakfastSerial ,

doing a quick grep on the source to find those messages, it appears that the image you have uses big endian integers on-disk and you are on a little endian machine. The SquashFS 4.0 format requires the image to be little endian, but prior versions did support the image to be either. From my understanding, `unsquashfs` then detects the byte-reversed magic number and goes down a compatibility code path for older image versions, which then terminates on the version number check.

Tampering with the SquashFS on-disk format seems to be somewhat popular with plastic router vendors, which is why the [sasquatch](https://github.com/devttys0/sasquatch) project exists, which collects a few patches against `unsquashfs` to support unpacking some vendor modified images.

**Comment by plougher** [comment]
As mentioned, this is an "unofficial" modified SquashFS filesystem, produced using modified tools.  The vendor may make the modified source available on their website, but, many do not for perhaps obvious reasons.

The tools here cannot support any "unofficial" variants.

Closing because this is neither a problem or bug with the tools.
