### ISSUE TITLE
Temporary storage for large filesystems

### ISSUE THREAD

**Issue by damoclark** [plougher/squashfs-tools#109]
Hey @plougher 

squashfs-tools is quite remarkable software.  Congrats.

I noticed ticket #60 presents as the same use case as mine.  Although I don't believe its a bug in squashfs-tools, but rather a scale issue.  I too am attempting to create a squashfs image from a backintime directory structure stored on an ext4 fs.  I too am running out of memory, both with the distribution version, but also with the vanilla version I just [downloaded](https://github.com/plougher/squashfs-tools/commit/06fc061ef426672576075f2989f52acd873c0141) and compiled from this repo.  

[plougher commented](https://github.com/plougher/squashfs-tools/issues/60#issuecomment-474519872):
> Mksquashfs needs to scan the filesystem and read the metadata (inodes, directory names etc.) and then cache that in memory. It also needs to cache the compressed metadata (inode table and directory table) because that is only written to the Squashfs filesystem after data blocks.
>
> If you have a very big filesystem, or one with many small files (i.e. low ratio between data and metadata), it may mean Mksquashfs will end up caching 2, 3, 4 Gigabytes of metadata or more, ontop of the -mem value. It entirely depends on the filesystem.

This I believe, is the situation exactly.  I run out of RAM before anything is written to the output image file.

[plougher continued](https://github.com/plougher/squashfs-tools/issues/60#issuecomment-483177341):
> I want you to be using a vanilla Mksquashfs, I want some more facts about your filesystem ... What is special about your setup or your filesystem. ... with no more information, there is nothing more I can do.

Happy to fill in the gaps with my situation.  Anything further that might help, let me know.  

[Backintime](https://github.com/bit-team/backintime) backup software [works as follows](https://unspecified.wordpress.com/2010/05/19/how-backintime-works/):

1. Tests whether the drive has changed since last snapshot (using rsync), and if not, quit.
2. cp -al <previous snapshot> <new snapshot>. This creates a complete recursive copy, but every single file is hard-linked to the old snapshot.
3. rsync -aEAX –delete-excluded –delete –chmod=Fa-w,D+w <current directory> <new snapshot>. This copies every modified file over the top of the existing hardlink (deleting the hardlink and creating a new file), and sets it to read-only.
4. Create a simple CSV file fileinfo.bz2 which contains each file’s original permission bits, owner and group.

Effectively, its a Linux implementation of Apple Timemachine, but without hardlinked directories.  

Thus, over time you end up with many hard linked files, such that you have the low ratio of data to metadata as you described.  Below are the statistics of the filesystem I am working with, although it's important to point out that there are other large files on this filesystem (that I am not attempting to squashfs).

```
$ df -i
Filesystem        Inodes     IUsed   IFree IUse% Mounted on
/dev/sda1      183140352 179466794 3673558   98% /mnt/hdd

$ df
Filesystem      1K-blocks       Used Available Use% Mounted on
/dev/sda1      5814152716 5814136444         0 100% /mnt/hdd
```
So I have 180M inodes in use.  According to dumpe2fs output for my filesystem, the inode size is 256 bytes.  So inode metadata alone (excluding xattr etc), 179,466,794 x 256B = 44GB.  My host has 8GB of RAM.

Admittedly, these filesystem characteristics are unusual, but it is still a perfectly valid filesystem, and within the scale of ext4 at least.  So the problem is that mksquashfs-tools has a scalability issue that will, over time, manifest more and more often as filesystem metadata get larger.  

e2fsck ran into this same scalability issue some time ago, as it too attempts to read all inodes into RAM during a fsck.  They implemented a [[scratch_files] stanza](https://linux.die.net/man/5/e2fsck.conf) option in its e2fsck.conf file that writes inodes (and other metadata) to a [TDB file](https://tdb.samba.org/) in the nominated directory.

```
$ sudo file <tmpfile>
<tmpfile>: TDB database version 6, little-endian hash size 179466794 bytes
```

It slows down fsck quite a bit naturally, but at least allows a fsck to run on a large filesystem when there is insufficient RAM to hold the metadata.

Obviously a considerable undertaking, but could a similar solution be implemented in mksquashfs?

Damien.

**Comment by plougher** [comment]
I can't decide whether you're a troll.

You bring up an already asked two year old issue https://github.com/plougher/squashfs-tools/issues/60, and so you know the cause and my explanation as to why Mksquashfs is like this.

You then mention e2fsck and its use of scratch files.  Thus trying to imply it is Mksquashfs which is somehow broken and non-scalable because it doesn't have that functionality.  But without any real basis to back up that assertion.

Finally, you say

>   Obviously a considerable undertaking, but could a similar solution be implemented in mksquashfs?

So you already know the problem and now you've answered your own question.

So *why* did you raise the issue?  To annoy, to cause an argument?

Sorry I'm not going to rise to the bait here.   Please just go away.

**Comment by damoclark** [comment]
Hi @plougher 

> I can't decide whether you're a troll.

Definitely not a troll.  My post is sincere, and my reference to the old issue was simply to highlight I have the same use case and to provide the information you asked of the person who made that report (and didn't bother to reply).  My apologies if my comments offended you.  That was not at all my intention.

> You then mention e2fsck and its use of scratch files. Thus trying to imply it is Mksquashfs which is somehow broken and non-scalable because it doesn't have that functionality. But without any real basis to back up that assertion.

To be clear, I did not imply mksquashfs is broken.  But yes, I did explicitly suggest that it has scalability issues (the tool, not the filesystem).  It cannot cope with filesystems with large metadata, without sufficient system memory to store it.  e2fsck had a similar problem and I simply highlighted how they solved it.  

I thought I articulated and evidenced the basis for that assertion pretty clearly.  Did I make a mistake somewhere?

> Finally, you say
>    Obviously a considerable undertaking, but could a similar solution be implemented in mksquashfs?
> So you already know the problem and now you've answered your own question.
> So why did you raise the issue? To annoy, to cause an argument?

I acknowledged that there was a potential obstacle to the solution I proposed, but I asked anyway because I don't profess to know everything and considered you might have a way around the obstacle, or perhaps a better solution entirely.

As I said, it is pretty cool what mksquashfs can do.  

> Sorry I'm not going to rise to the bait here. Please just go away.

I'm not trolling you.  But you have made your position brutally clear.  I shan't bother you again.

Damien.

**Comment by plougher** [comment]
> Hi @plougher
> 
> > I can't decide whether you're a troll.
> 
> Definitely not a troll.

Well that's good to know.  I've been maintainer of Squashfs for nearly 20 years (since 2002), and, I've lost count of how many people has shown up just wanting to cause trouble.  Open source seems to attract "mud slingers" especially over the last couple of years  and especially if your software becomes widely used.     If you try to reason with them, it just encourages them, and that simply makes the argument worse.

It is hard not to become cynical and defensive.   I wish it was not the case.


> My post is sincere, and my reference to the old issue was simply to highlight I have the same use case and to provide the information you asked of the person who made that report (and didn't bother to reply). My apologies if my comments offended you. That was not at all my intention.

No, they didn't offend.  But, the previous issue is a case in point.  Some-one showed up, I spent a lot of time on the issue, and then they simply disappeared.  So I wasted that time.


> 
> > You then mention e2fsck and its use of scratch files. Thus trying to imply it is Mksquashfs which is somehow broken and non-scalable because it doesn't have that functionality. But without any real basis to back up that assertion.
> 
> To be clear, I did not imply mksquashfs is broken. But yes, I did explicitly suggest that it has scalability issues (the tool, not the filesystem). It cannot cope with filesystems with large metadata, without sufficient system memory to store it. e2fsck had a similar problem and I simply highlighted how they solved it.
> 
> I thought I articulated and evidenced the basis for that assertion pretty clearly. Did I make a mistake somewhere?
> 

There is a difference between keeping all the stuff in memory for convenience (either because it makes the program easier to write, and/or it makes the program faster to run), and keeping all the stuff in memory because it forms the "working set" (see Wikipedia for an explanation).

Mksquashfs stores "all the stuff" in memory both for convenience, and because it forms the programs working-set.  It is constantly scanning the entirety of the metadata to do the work and make its computations.

In other-words, if the "in memory data" was simply a snapshot of the filesystem, it would be possible to write it out to a scratch file on the basis it won't need to be used again "for a while".    But it is impossible if that data is frequently accessed, as part of the programs working set.

The swap partition where anonymous memory (i.e. allocated data, not backed by a file on disk) is written to free up space in RAM, is effectively a scratch file.   If Mksquashfs (any other program) produced 32 GB of data, but none of it was accessed/referred to again "for a while" it would simply end up on the swap partition, but there wouldn't be a *huge* slow down in the program speed.   It is only when the working set becomes too big for RAM, that a huge slow down occurs because the operating system thrashes (again see thrashing in Wikipedia for an explanation), constantly loading and reloading from disk.

That's why writing the data  out to a scratch file won't work with Mksquashfs.  If it did work, then using swap to store it would already work too.

> > Finally, you say
> > Obviously a considerable undertaking, but could a similar solution be implemented in mksquashfs?
> > So you already know the problem and now you've answered your own question.
> > So why did you raise the issue? To annoy, to cause an argument?
> 
> I acknowledged that there was a potential obstacle to the solution I proposed, but I asked anyway because I don't profess to know everything and considered you might have a way around the obstacle, or perhaps a better solution entirely.
> 

if I knew a quick and easy way to do it then it would be fixed,  and you wouldn't be asking the question.

As I explained it is all to do with the "working set".   The only way to solve the problem is to essentially reduce the "working set".  It might be possible to reduce the working set by partitioning the data, essentially splitting it into pieces to reduce RAM, and then knitting the separate pieces back together.  But Squashfs is a compressed filesystem, you have to know everything up front when compressing, because you can't leave placeholders to be filled in later, as it will alter the compression.

You can already do partitioning and knitting back together the pieces yourself in a basic way.   Basically you can split your filesystem (with it's 44GB of inode data) into four separate pieces (by directory or otherwise), and run Mksquashfs on each piece.  This will reduce the amount of RAM to a workable amount (if not try splitting into 8).  You'll end up with 4 Squashfs filesystems which you can mount together.

Obviously, if you have duplicate files or hard-links which cross the separate pieces they won't be detected.  Obviously neither can you update each Squashfs filesystem to add that information afterwards, because they're now compressed.

So if you do have duplicates and hard-links spread across the filesystem, partitioning doesn't work unless you're prepared to miss some (and you don't know how many, 10%, 20%, more?)

At this point you may understand about the entirety of the metadata being the working set.

Also you may understand as author of Squashfs (who is maintaining it for free in my spare time) that I have to prioritize requests.   Requests which more people are asking for get priority, requests which takes less time get priority.  This way I get more "bang for my buck". 

Plus as someone with little free time to work on Squashfs, I get piqued when someone suggests I spend months "fixing" Mksquashfs, when they could buy some more RAM and fix it themselves.

It just doesn't seem a good use of my time.  In fact so much so, it will always be a very low priority.  Unless of course a miracle occurred and a company using Squashfs (say one of the very large multi-billion dollar companies) actually paid me some money.  Perhaps then I could take a paid sabbatical, and do all the stuff people want.  Or buy a new computer for Squashfs development, one which wasn't seven years old and also has 8 GB of RAM (in case you get the impression I'm going to have a huge system with a minimum of 32 GB and have the attitude anything less is someone else's problem).
 

> As I said, it is pretty cool what mksquashfs can do.
> 
> > Sorry I'm not going to rise to the bait here. Please just go away.
> 
> I'm not trolling you. But you have made your position brutally clear. I shan't bother you again.
> 

Well, I apologize for the initial harsh response, because you came across as another troll.

I hope the above is nicer in tone.  But, ultimately, there is not a lot I can do given the circumstances. 

Phillip

> Damien.

**Comment by damoclark** [comment]
I appreciate the time you have taken to explain the problem Phillip, and I now have a better understanding.  

The reason I suggested TDB was because that was the solution that the e2fsck folk used to solve the problem of dealing with a large working set.  However, I hadn't considered that using an on-disk indexed database would be no more effective than allowing for sufficient swap space and with modern sophisticated VM algorithms.  e2fsck is sometimes needed when swap isn't available (i.e. failing boot/root volume), but an alternate read/write filesystem might be, and perhaps that is why they chose that solution.  

I hadn't considered mksquashfs as a data archive tool, and it is a really novel format to use for this.  Can extract data from the fs image using unsquashfs, but can also mount it too.  And its all compressed and indexed.  Just not practical for my Back-in-time archive. 

Damien.

**Comment by pixelplanetdev** [comment]
just wanted to show up and say that i am running into the same issue with a year worth of backups. Thanks for explaining what's going on. I will just split it into parts.
