### ISSUE TITLE
Directory size limit

### ISSUE THREAD

**Issue by Man-0-waR** [plougher/squashfs-tools#118]
mksquashfs.c
```
		if(byte_size >= 1 << 27)
			BAD_ERROR("directory greater than 2^27-1 bytes!\n");
```
Where this limitation (128MB) comes from? Can't create volume image with very large number of files in directory.
In [kernel docs](https://www.kernel.org/doc/Documentation/filesystems/squashfs.txt) it is said "unlimited".

**Comment by plougher** [comment]
As the above commit says, 128 Mbytes was the maximum directory size for the old Squashfs 3.x layout.  This should have been updated to the 4.0 layout limit of  4 Gbytes, and it now has been.

 Your comment regarding "unlimited" in the kernel documentation is because you misunderstand how "unlimited" is being used in filesystems context.

Look at this webpage, and scroll down to the section for "ext4" https://stackoverflow.com/questions/466521/how-many-files-can-i-put-in-a-directory.  Here you'll see

<pre>
ext4:
Maximum number of files: 2^32 - 1 (4,294,967,295)
Maximum number of files per directory: unlimited
Maximum file size: 244 - 1 bytes (16 TiB - 1)
Maximum volume size: 248 - 1 bytes (256 TiB - 1)
</pre>

How can the maximum number of files be 2^32 - 1, but, the number of files per directory be listed as unlimited?

This is because "unlimited" isn't being used in the sense of _infinity_, but in the sense there is no file count, the filesystem  is not saying "I'm going to store 10,0000" files, and once you've got to that amount, you can't add any more.  The filesystem doesn't care how many files are in the directory, it doesn't keep tabs on it.

In this case (and with Squashfs) because there is no file limit, the effective limit on the number of files in a directory is the maximum directory size.  But that can vary depending on the sizes of the directory names.    Filesystem documentation indicates this by using "unlimited"  and should be understood as described.
