### ISSUE TITLE
-all-root defeats pseudo uid/gid

### ISSUE THREAD

**Issue by philhofer** [plougher/squashfs-tools#132]
When `-all-root` (or one of the other options that sets `global_uid` and `global_gid`), those values end up overriding the uid and gid specified via `-p` or `-pf`.

I ended up discovering this behavior by accident because I thought if I specified `foo m 644 user user` for a pseudo-file that I could selectively override the file ownership.

It would be great to update the docs to make clear that `-all-root` and friends always win as far as file ownership goes.

Similarly, it would be great to have an option to specify that the default ownership takes lower rather than higher priority than the pseudo-file options. In the mean time I've patched my source to replace `lstat()` in `mksquashfs.c` with calls to a wrapper that sets `st_uid` and `st_gid` to some default values. I think that's most of what would be necessary to implement `-default-uid` and `-default-gid` options.

Happy to send patches for either/both of the items above.

Cheers.

**Comment by plougher** [comment]
-all-root etc was added by request to do exactly that, to over-ride all uids and set them to root.  But, -all-root etc are specialised options, which were brought in to be used in embedded Linux, where such an ability is often needed.  For most people these options are rarely or never needed.

It is impossible to add options that do something only slightly different to an existing option, because in that way you will end up with literally hundreds of options that do almost the same thing, because everyone has different ideas, use-cases or ways of doing things.

The best way to avoid the above is to make options flexible or generic, which is what I've always tried to do.  The above specialised narrowly focussed options were an exception, because they are common in embedded Linux.

Anyway, because I have been asked repeatedly to add slightly different options, I spent a long time adding a mini-language to Mksquashfs which allows users much more control over filesystem building than just using options.  This was added in the latest release (4.5), and is called "Actions".

These allow you, for example, to set uid/gid to default values.

% mksquashfs testdata sqsh -action "guid(dovecot, postfix)@true"

This will set all uids to dovecot, and all gids to postfix.

You can also selectively decide which files to apply the guid() action to, by replacing true with an attribute test operator (or combination of operators).

For example

% mksquashfs testdata sqsh -action "guid(dovecot, postfix)@name(*.txt)"

Apply guid() action to all files which match the "*.txt" filename wildcard.

% mksquashfs testdata sqsh -action "guid(dovecot, postfix)@filesize(>4K)"

Apply guid() action to files larger than 4K in size.

% mksquashfs testdata sqsh -action "guid(dovecot, postfix)@filesize(>4K) && name(*.txt)"

Apply to files larger than 4K and which match "*.txt" filename wildcard.

The Actions usage README is https://github.com/plougher/squashfs-tools/blob/master/ACTIONS-README.

Actions are evaluated before pseudo files.

**Comment by philhofer** [comment]
Perfect, thanks.
