### ISSUE TITLE
mksquashfs throwing error Is a directory(21): 

### ISSUE THREAD

**Issue by ck1703** [plougher/squashfs-tools#135]
While running mksquashfs command seeing Is a directory error

mksquashfs /tmp/test.bin /tmp/squashfs%Ver%2_0.bin -mkfs-time 1636019834 

Parallel mksquashfs: Using 2 processors
Creating 4.0 filesystem on /tmp/squashfs%Ver%2_0.bin -mkfs-time 1636019834 , block size 131072.

[=|                                                          ]   500/15043   3%
[======\                                                     ]  1700/15043  11%
[==========/                                                 ]  2600/15043  17%
[=================|                                          ]  4400/15043  29%[11-12:18:07:51.738] main.c:254 error Is a directory(21)

**Comment by plougher** [comment]
You have not provided much information here, but, I can make an "educated guess" as to what is happening.

Mksquashfs should never make the mistake described here, which is trying to open a directory as a regular file (hence the error message).  The reason for this is because Mksquashfs "stats" the file to obtain the file type, and then processes it accordingly.

The most obvious reason for the above error is because the file changed type between stating the file, and then reading it.  That is it changed from a regular file into a directory.

Mksquashfs (like all archiving programs) isn't designed to archive files which are actively changing while it is archiving.

**Comment by ck1703** [comment]
My application was calling mksquashfs command immediately after doing unsquashfs. I suspect due to this file system didn't get enough time to settle down. Added some sleep between unsquashfs and mksqushfs. Now not seeing the issue
