### ISSUE TITLE
Add manpages

### ISSUE THREAD

**Issue by mystiquewolf** [plougher/squashfs-tools#136]
This is a feature request to add manpages.

See here: https://bugs.archlinux.org/task/72822

**Comment by neitsab** [comment]
To be specific, the reason for the Arch package not providing the manpages is because the [release tarball](https://github.com/plougher/squashfs-tools/releases) downloaded doesn't itself include the [`generate-manpages`](../tree/master/generate-manpages) folder nor the [prebuilt manpages](../tree/master/manpages), making [this line of the makefile](../blob/master/squashfs-tools/Makefile#L425) inoperative.

I don't know how tagged tarball are generated, but it would be great if you could include those folders in them for the upcoming release 😊

**Comment by plougher** [comment]
Squashfs tools 4.5.1 released.   This has manpages added, and they are in the tarball.

**Comment by neitsab** [comment]
Nice, well done and thank you! 🙏
