### ISSUE TITLE
Wish for full-precision timestamp output from unsquashfs

### ISSUE THREAD

**Issue by ldoolitt** [plougher/squashfs-tools#137]
I'm one of those weirdos that takes [reproducible builds](https://reproducible-builds.org/) seriously.
Chasing down reproducibility problems in the output of mksquashfs makes me wish that unsquashfs expose all state held in the squashfs file.
Right now (checked as of git commit 19fcc936) unsquashfs -ll only emits timestamps to the minute, ignoring the tm_sec field held in the file.
Changing a printf deep inside unsquashfs.c to

`printf("%d-%02d-%02d %02d:%02d:%02d %s", t->tm_year + 1900, t->tm_mon + 1,
              t->tm_mday, t->tm_hour, t->tm_min, t->tm_sec, pathname);`

fixes this for me.
For backwards-compatibility purposes, I bet y'all really want to add a command-line switch to enable this expanded output.

**Comment by plougher** [comment]
Well as you said "For backwards-compatibility purposes, I bet y'all really want to add a command-line switch to enable this expanded output."

I'm not opposed to adding new command-line options, but, if I agreed to every request to do so, the command options list would now be a mile long  :-(  This doesn't do anyone any good because a "mile long options list" becomes something no-one ever reads.   So the option may as well not be there, because no-one will ever find it.

In these cases where there is no hard or fast answer, I generally wait to see how many others ask for this option.  If a lot of people think this is a good thing, then it will become worth adding it.

You seem perfectly capable of modifying your copy of Unsquashfs to do the above, and unless you have an over-ridding need for this to be in the "official tools", there doesn't yet seem a need to add this.

But, I'll keep this issue open, and see if I get any other comments on it, yes or no etc.

Are you happy with this?

Phillip

**Comment by ldoolitt** [comment]
Yes, I'm "perfectly capable of modifying your copy of Unsquashfs to do the above."  But I also collaborate with others, and don't like passing around patches any more than I have to.

Crazy idea: since Aug 2019 you have the "-UTC" switch, which may attract the same target audience.  Could that switch have the side-effect of selecting seconds-resolution output?  Or does that violate the "principle of least surprise"?
