### ISSUE TITLE
Recommandation for squashfs usage as dataset container

### ISSUE THREAD

**Issue by nlgranger** [plougher/squashfs-tools#141]
This is not actually a question but I'd like to have suggestion for an unconventional use of squashfs.
My lab is exploring the idea of using squashfs images to move around and mount datasets. Our rationale for that was:
- Need to store datasets with millions of small files, often images, without killing the distributed filesystem
- Need read-only, random access to files
- Latency is not critical (files are fed to a queue)
- Posix filesystem API rather than S3, hdf5 etc.
- Need to move the data locally to compute nodes

Squashfs seems to tick all our criteria and we are running some experiments with it to check the performance under load.

Do you have any suggestions regarding the options to create the images? For instance:
- how to choose block size?
- is it bad to have directories with large number of files?
- should we enable compression of data, inodes, fragments? (the distributed and local data storage are rather fast and we'd rather spare CPU time for computation if possible)
- what about the other options: sort, pad, tailends, etc. ?

Thank you for any suggestions you can provide. I can also write a small feedback on our experiments here if you are interested.

**Comment by plougher** [comment]
It isn't really my responsibility to give usage advice ...

But, the scenario you describe is similar to  cases where Squashfs has been adopted.  This is in "high performance" large data environments dealing with many small files.  Instances are "Singularity" which use Squashfs to improve performance when using distributed filesystems.

By and large the Mksquashfs defaults should be used.  They are a balance between compression and I/O performance.   Compression of data, inodes and fragments optimise I/O performance.  It is not bad to have directories with a large number of files, because Squashfs handles that.  The sort, pad and tailends options are specialised options which are only needed in certain circumstances.  In your case you can ignore them.

**Comment by nlgranger** [comment]
Got it! Thank you very much for your explanations (and more generally for your work on squashfs).

FYI, my objective was to write a dataset caching daemon for a clusters: https://github.com/CEA-LIST/scratch_manager
It works quite well and is considerably cheaper and simpler than specialized hardware or software solutions.
