### ISSUE TITLE
mksquash fails on duplicate libtorch_cuda.so

### ISSUE THREAD

**Issue by NathanielMiddleton** [plougher/squashfs-tools#148]
squashfs-tools-4.3-0.21

Scenario: mksquashfs fails during DUPLICATE check, works fine with -no-duplicates

User is using singularity to run a container, singularity calls:
/usr/sbin/mksquashfs /scratch/fast/3883388/build-temp-833378565/rootfs /scratch/fast/3883388/bundle-temp-191484576/squashfs-457482961 -noappend -all-root

mksquashfs runs until it reaches
file /envs/suite2p/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so, uncompressed size 439367144 bytes DUPLICATE
which I believe it is actually landing on 'libtorch_cuda.so' based on lsof output.

libtorch_cuda.so is a 1.2G file, that is repeated in 3x locations:
1.2G    ./rootfs/envs/event_detection/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
1.2G    ./rootfs/envs/ophys_etl/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
1.2G    ./rootfs/envs/suite2p/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so

Running this mksquashfs command with '-no-duplicates' allows the image to complete... but seeing as this is run with singularity(AFAIK user is not able to specify no dups via singularity)... I am trying to figure out why this is failing... and if there is a known bug/fix for this?

**Comment by plougher** [comment]
I need to know more information about the Mksquashfs version, your system,  etc.  Please answer the following questions.

1. What does "mksquashfs -version" report?

2. What distribution are you using?

3. What architecture?  (probably x86_64), how much main memory?

4. What options were passed to Mksquashfs, i.e. block size etc.

5. How does it fail during duplicate checking?  Does it crash?  An output of what is printed to stdout and stderr, and whatever the system produces would be helpful.  You can use -no-progress to get rid of the progress bar (if it is being displayed).

6. Ideally you should supply a reproducer, which is the set (or sub-set) of data which causes the issue, and allows myself to reproduce it on my system.

You ask if this is a known bug.  Unfortunately, there have been no bugs/issues of this kind raised against vanilla Mksquashfs 4.3, and Mksquashfs 4.3 has been around since 2014, which is a long time.  So there has to be something unusual which is causing the issue, which hasn't happened before (or been reported).

In this situation the usual response is to ask the user to upgrade to the latest version, and re-test.   This helps to narrow the problem down.  So if there are newer packages available, or you can download the latest source, and compile it, that would help.

**Comment by plougher** [comment]
No response, so closing due to lack of reproducibility.
