### ISSUE TITLE
No documentation on sort option

### ISSUE THREAD

**Issue by rogerbinns** [plougher/squashfs-tools#15]
There isn't any documentation or guidance on the sort option for squashfs.  Example questions:

- What is the benefit/drawback?
- Does it have any relevance to media with low latency random access (eg SSD, sdcard)?
- When listing a directory does it include the subdirectories/whole tree too?

**Comment by plougher** [comment]
There is sadly some "bad" history associated with the sort option.  Not with the code itself which is very good, bug free, and maintained.  The "badness" is more associated with why it was implemented in the first place, back in Squashfs 1.x days or 2003.

At that time a company approached me asking for this feature, with a very tight milestone, and promised payment if I could implement it within that tight milestone.  I duly implemented the code, delivered it and well you can probably guess the rest.  No payment.  At this point documenting the feature seemed like gift wrapping the deliverable, when I knew I wasn't going to get anything.  So I didn't.

When it came to the next release I still didn't want to document it, but, I didn't see any sense in spending time to remove it also, and so it was released as a minimally documented feature.

To answer your questions:
 
> What is the benefit/drawback?

Originally, as in isofs, it was designed to place files used at the same time together, as this will improve seek time.  Since Mksquashfs 2.0 it not only places files together, but also places them in the same fragments.  This has decompression time advantages even if seek time is minimal (as in SSD).

The only drawbacks is if your sorting doesn't reflect the actual access patterns.

>  Does it have any relevance to media with low latency random access (eg SSD, sdcard)?

Yes, it sorts files so they're packed into the same fragments.

> When listing a directory does it include the subdirectories/whole tree too?

Yes, anything in a directory including sub-directories inherits the priority of the directory, unless of course you change the priority of something within it with an explicit priority.  Basically everything inherits the priority of their parent, and that priority stays unless you explicitly change it.

**Comment by rogerbinns** [comment]
Thanks for the details, and the unfortunate way this feature happened.

I was able to use it and things started a little bit faster as a result.  I also had to work out if the sort file lines were "number path" or "path number".  Turned out to be the latter.

I'm happy with the documentation above.
