### ISSUE TITLE
Allow `mksquashfs` to run without any source file

### ISSUE THREAD

**Issue by runapp** [plougher/squashfs-tools#156]
Now the mksquashfs cli tool requires at least one source argument. So one can't just add files by pseudo definitions only. Would you consider allowing mksquashfs to do "dummy" runs? e.g. mksquashfs a.squashfs can create an empty squashfs image, and mksquashfs a.squashfs -p 'now f 644 0 0 date' can generate an image with only one dynamic file.

**Comment by plougher** [comment]
You can do this now using only pseudo files.

```
phillip@linux:/tmp> mksquashfs - a.squashfs -p "/ d 644 0 0" -p "now f 644 0 0 date"

phillip@linux:/tmp> unsquashfs -ll a.squashfs
drw-r--r-- root/root                26 2022-02-21 20:16 squashfs-root
-rw-r--r-- root/root                32 2022-02-21 20:16 squashfs-root/now

phillip@linux:/tmp> sqfscat a.squashfs now
Mon 21 Feb 2022 08:16:06 PM GMT
```

The differences are:

1.  You must add a root directory (/), because this is the minimum valid Squashfs filesystem.  Empty filesystems can't exist because there must be a root directory to mount it in Linux.

2.  No sources on the command line is indicated by using '-'.

**Comment by runapp** [comment]
Thank you. Would you mind adding the usage of `-` to the document? Or maybe better, to add the whole example.

**Comment by plougher** [comment]
It is mentioned in the documentation for the 4.5 release of Squashfs-tools.

See https://github.com/plougher/squashfs-tools/blob/master/README-4.5.

Line 44

```
1.9 Mksquashfs now allows no source directory ( specified as - )
    to be specified, with all input from pseudo file definitions
    (see section 12).
```

and

```
12. Mksquashfs now allows no source directories ( specified as - )
==================================================================

Mksquashfs has removed the requirement to specify any physical source
directories, and a Squashfs filesystem can now be built entirely with
Pseudo definitions.

For example the following command line

% mksquashfs - img.sqfs -p "/ d 777 phillip users" -p "/hello l /tmp/typescript" -p "/link L hello"

Will create a root directory, a file created by a reference to a file
within the filesystem, and create a hard link to it.
```

Squashfs-tools 4.5 was released last year and you may still have an older version in your distribution.  Which is why it won't be mentioned in the documentation.

**Comment by plougher** [comment]
Most distributions have very out of date Manpages too, because the third-party that wrote them, stopped updating them.

I have added Manpages, and these will document the feaure.

**Comment by plougher** [comment]
I noticed you can't use the '-' option on appending, due to an oversight.  This has been fixed, and you get the latest source code from this repository.

**Comment by runapp** [comment]
> It is mentioned in the documentation for the 4.5 release of Squashfs-tools.

 Indeed. My squashfs-tools is at `4.4-1.1`. I really should have checked the latest release first.
