### ISSUE TITLE
Adding files to existing path of existing image by pseudo definition silently fails

### ISSUE THREAD

**Issue by runapp** [plougher/squashfs-tools#157]
After running the following commands, I found `d1/f3` and `d2/f4` are missing in `b.squashfs`. I didn't find any error log about these two files. Same results can be get with `-pf` pseudo-file option.
I also noticed that during the 2nd run of `mksquashfs` for `b.squashfs` there's a message writing `Pseudo file "d2" is a pre-existing file in the filesystem being appended to.  Ignoring.`.

```shell
mkdir test && pushd test

touch dummy
mkdir d1
echo A > d1/f1
mkdir d2
echo B > d2/f2

mksquashfs d1 d2 a.squashfs \
-p 'd1/f3   f 644 0 0 echo C' \
-p 'd2      d 755 0 0' \
-p 'd2/f4   f 644 0 0 echo D' \
-p 'd3      d 755 0 0' \
-p 'd3/f5   f 644 0 0 echo E'

mksquashfs d1 d2 b.squashfs
mksquashfs dummy b.squashfs \
-p 'd1/f3   f 644 0 0 echo C' \
-p 'd2      d 755 0 0' \
-p 'd2/f4   f 644 0 0 echo D' \
-p 'd3      d 755 0 0' \
-p 'd3/f5   f 644 0 0 echo E'

unsquashfs -ll a.squashfs
unsquashfs -ll b.squashfs
```

**Comment by plougher** [comment]
Mksquashfs can add files (not just pseudo files) to existing filesystems by *appending* them to the existing image.

But, this is only a limited form of extension, where extra files and directories can be added to the root directory.

It does *not* allow extra files and directories to be added to pre-existing directories, because that requires *re-writing* the directories.  This is impossible with an append only mode of extension.

So, for instance if your filesystem had a root directory with a directory called "example" ....  You add another directory to the root directory called "example2", or add a file called "file".  But you cannot add another file to the pre-existing directory called "example".

Adding the ability to add to pre-existing directories has been a low-priority TODO item for many years, and it will remain so, given Squashfs doesn't have any funding or pay any money.

**Comment by plougher** [comment]
Oops, wrong issue.  Please ignore.
