### ISSUE TITLE
long -> int conversion on 64bit platforms

### ISSUE THREAD

**Issue by m94mni** [plougher/squashfs-tools#171]
Tried updating to running from HEAD and ran into a conversion issue:

third_party/squashfs/squashfs-tools/unsquashfs.c:639:43: error: implicit conversion from 'long' to 'int' changes value from 9223372036854775807 to -1 [-Werror,-Wconstant-conversion]
                int len = (bytes - count) > SSIZE_MAX ? SSIZE_MAX : bytes - count;

**Comment by m94mni** [comment]
size_t len

seems to resolve this

**Comment by plougher** [comment]
That is a CLANG issue, go and tell them to fix it.

From the Linux manpage for READ(2)

```
According to POSIX.1, if count is greater than SSIZE_MAX, the result is implementation-defined;
see NOTES for the upper limit on Linux.

NOTES
The types size_t and ssize_t are, respectively, unsigned and signed integer data types specified by POSIX.1.

On  Linux,  read() (and similar system calls) will transfer at most 0x7ffff000 (2,147,479,552) bytes,
returning the number of bytes actually transferred.  (This is true on both 32-bit and 64-bit systems.)
```

GCC returns  the correct 2GB value for both 32 and 64 bit systems.

Also you're starting to be a asshole.  FUCK OFF

**Comment by Dr-Emann** [comment]
I think this is worth changing.

The lines in question are:
```c
int len = (bytes - count) > SSIZE_MAX ? SSIZE_MAX : bytes - count;
res = read(fd, buff + count, len);
```

On a 64-bit system, in the case `bytes - count == (long long)INT_MAX + 1`, `len` will equal `-2147483648`. When cast to a `size_t` (the type of the 3rd parameter to read), we ask to read `18446744071562067968` bytes. This is much more that we will have space for (and more than `SSIZE_MAX`, so implementation defined). Luckily, we _are_ saved by linux's limit only ever returning slightly less than INT_MAX.

**Comment by Dr-Emann** [comment]
Or worse, `(bytes - count) == ((long long)INT_MAX + 1) * 2` (4294967296), when cast to `int` is `0` (read will return 0, which we'll treat as an early EOF)

I haven't found any ways that this function would end up being called with such large numbers, though. It's almost always called with `block_size`. That said, I think everything is fixed by changing the type of `len` to `size_t`.

**Comment by plougher** [comment]
All the talk of using a "size_t" completely misses the point.

```
int len = (bytes - count) > SSIZE_MAX ? SSIZE_MAX : bytes - count;
```

The whole point of that line is to limit the transfer length to 2^31, which fits into a signed int without any issue.

Moving to a "size_t" merely fixes the symptom that the line isn't limiting the length to 2^31 using the CLANG compiler.  It does nothing to fix the cause.  Moving to a "size_t" will still pass more than 2^31 bytes to read(), which is the whole purpose of that line.  So it doesn't fix the real problem.

The cause is SSIZE_MAX is so large on CLANG that it renders the line useless.  You might as well completely remove the line, and just pass "bytes - count" directly to read().

The real fix is ensure the line always limits the value to 2^31 or less.  This is what is done in the above commit.    And it doesn't involve using a "size_t" either.   Because once the real cause is fixed, the existing signed int is perfectly adequate.
 
If the line was working correctly, there would be no need to move to a "size_t".

**Comment by Dr-Emann** [comment]
There's certainly no difference with the definition of `SSIZE_MAX` between gcc and clang, it will be 2^63 on a 64 bit system, and 2^31 on a 32 bit system (and 2^15 on a 16 bit system): https://c.godbolt.org/z/vxjKaEnnj, and they of course produce identical assembly for the original line of code: https://c.godbolt.org/z/GrxaGPEKo

There's two separate things in the man page:

* Passing count > SSIZE_MAX invokes implementation-defined behavior
* Linux will copy at most `0x7ffff000` bytes

It is perfectly well defined behavior to pass values `> 0x7ffff000`, or `> INT_MAX` (as long as the value is `<= SSIZE_MAX`) to `read`. On linux, at least, it will always perform a partial read when given such input, but it is fully defined behavior.

The commit above does solve the issue of truncation in all cases, despite having inaccuracies in the commit message regarding "unreliability" of SSIZE_MAX.
