### ISSUE TITLE
sqfstar -root-uid does not actually set root uid

### ISSUE THREAD

**Issue by m94mni** [plougher/squashfs-tools#173]
Per docs
% sqfstar -root-uid 0 -root-gid 0 image.sqfs < archive.tar

should set the uid and gid of the root directory. This does not seem to actually happen. 

-root-mode does seem to work.

Note that sqfstar can end up creating several intermediate directories with owner = getuid() (and similarly gid and mode), not only the root. It may be worth considering having the -root-* options apply to all such directories rather than only root.

Example:

$ mkdir xyz
$ touch xyz/file.txt
$ tar cf image.tar xyz/file.txt
$ tar tvf image.tar
-rw-r--r-- mikaeln/primarygroup 0 2022-03-18 21:01 xyz/file.txt
$ mksquashfs - image.sqfs -tar -root-uid 0 -root-gid 0 -root-mode 0700 <image.tar 
$ unsquashfs -ll image.sqfs 
drwx------ mikaeln/primarygroup     26 2022-03-18 21:02 squashfs-root
drwxr-xr-x mikaeln/primarygroup     31 2022-03-18 21:02 squashfs-root/xyz
-rw-r--r-- mikaeln/primarygroup      0 2022-03-18 21:01 squashfs-root/xyz/file.txt

I would naively expected the outcome to be
$ unsquashfs -ll image.sqfs 
drwx------ root/root     26 2022-03-18 21:02 squashfs-root
drwx------ root/root     31 2022-03-18 21:02 squashfs-root/xyz
-rw-r--r-- mikaeln/primarygroup      0 2022-03-18 21:01 squashfs-root/xyz/file.txt

**Comment by plougher** [comment]
There are two separate issues here:

1. First the -root-* options only affect the root inode.   That is why they're called -root-*.      These options are needed because tar files never define the root directory.  But they are also needed for options also like -cpiostyle.

2. The fact that tarfiles may not define intermediate directories in a pathname is a separate issue.
    Sqfstar and Mksquashfs set these undefined intermediate directories to uid/gid ownership and mode of drwxr-xr-x.

So, number 2 is not a bug it is expected behaviour.  If you'd like some option to change the default behaviour, then add them as an issue, and I'll consider it for the next release.

Number 1 is a bug, it looks like the code to implement those options was never implemented.  This is an oversight, and it will get fixed for the next release.
