### ISSUE TITLE
Quick modification of squashfs

### ISSUE THREAD

**Issue by dani1993l** [plougher/squashfs-tools#174]
Hi all,
I am new to the squashfs world and was wondering if there was a way to quickly add a file to a non-root directory of a given squashfs image, without mounting and recompressing the image. I found such a discussion on [stakcexchange](https://unix.stackexchange.com/questions/375191/append-to-sub-directory-inside-squashfs-file), though I hoped I could get a more technical answer regarding the possibility of such an implementation - Is it possible? How would one approach such a task? Is there a  reason why this has not yet been implemented that I am missing?

Any light shed on this issue would be very appreciated, as I am considering attempting to implement this myself.
Thanks and apologies if this is not the place for such an inquiry

**Comment by plougher** [comment]
In theory what you want to do can be done.  But in practise it is unwise to do that, because decompressing and recompressing is by far the most reliable operation and produces a better more optimised filesystem.

The discussion on stackexchange is actually a good "non-technical" explanation of how appending works with Mksquashfs.   It is incremental, which means you can add data to end of the "data section", then update the root directory information in the metadata and then rewrite it to the end of the filesystem, after the data section.

The reason why it can be done to the **_root directory_** and not to any other directory is **_because_** Squashfs is a compressed and tightly packed filesystem, without any empty space.  It is like building a brick wall - you can build it and a month or so later come back and add a couple of extra layers of bricks.  But, you can't decide to add a couple of nice different colour bricks to the existing wall layers, because there's nowhere to put them.  What you would have to do is completely dismantle the wall, and rebuild it, putting the different colour bricks where you want them.

That is obviously a non-technical explanation, but, it explains that **_where_** you put the information is as an important part of the filesystem as the information is itself.

In technical terms, filesystems for efficiency (including Squashfs) rely on a concept called "locality of reference".  It basically means that files in the same directory are likely to be accessed at the same time, and files in the same directory or close directories are likely to be similar to each other.  Squashfs packs small files together into large blocks and compresses them together.  The more similar the files are, the better the compression ratio.   

So when you're building the filesystem you put all the files where you can get best compression and best I/O performance.

Afterwards you can't add an additional file to a pre-existing directory, because there is no space, and all the optimising has already been done.

So to add an additional file means taking the filesystem apart and redoing the positioning and optimisation.   Which is no different to decompressing/mounting the filesystem and recompressing it.  In fact is is **_worse_** and  more unreliable, because you're not creating a copy where you get to keep the original filesystem if something goes wrong.  If something goes wrong you can end up with data loss and an unmountable filesystem.
