### ISSUE TITLE
Number of symbolic links/uncompressed size reported changes between invocations of `mksquashfs` on the same tree

### ISSUE THREAD

**Issue by cr1901** [plougher/squashfs-tools#176]
For reasons I don't remember (benchmarking?), I wanted to run `mksquashfs` on the same tree one day apart. The filesystems created appear to be fine, but I was worried about the reported filesystem information when `mksquashfs` was done. 

`mksquashfs` reports that the uncompressed/compressed filesystem size, inode size, directory size, number of inodes, and number of symlinks differ between the below three runs, when I did not (intentionally) touch the tree at all between runs. I wouldn't expect any of these numbers to change between reproducible builds.

And even if reproducible builds are off, I would only expect the compressed filesystem, compressed inode size, compressed directory size, and _possibly_ number of inodes to change (affected by how well fragments compress?).

My question is: Should these reported statistics change between invocations of `mksquashfs`, reproducible or not? _Unfortunately, this so far was the smallest tree where I could duplicate these results._

Idk if this is a bug, I'm making an issue just in case while it's fresh in my head. I won't have time to look into this until next week.

## Version

All images were created using ` mksquashfs ../../../backup/HTS54501/ netbook.squashfs* -b 1M -comp xz -Xdict-size 100%`, and `mksquashfs` help claims reproducible builds are the default.

```
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ mksquashfs -version
mksquashfs version 4.4 (2019/08/29)

william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ uname -a
Linux xubuntu-dtrain 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### First and Second Run

When I mount both images using `sudo mount -o loop` (first image in `old`, second image in `new`) Running `rsync -aHphivn --compare-dest=../new/ old/ cmp` shows that the contents of `old` and `new` are identical. 

#### First Run

```
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ mksquashfs ../../../backup/HTS54501/ netbook.sqaushfs -b 1M -comp xz -Xdict-size 100%
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on netbook.sqaushfs, block size 1048576.
[===================================================================|] 334984/334984 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 1048576
        compressed data, compressed metadata, compressed fragments,
        compressed xattrs, compressed ids
        duplicates are removed
Filesystem size 23295521.76 Kbytes (22749.53 Mbytes)
        77.16% of uncompressed filesystem size (30191010.24 Kbytes)
Inode table size 3314212 bytes (3236.54 Kbytes)
        17.65% of uncompressed inode table size (18777789 bytes)
Directory table size 10483752 bytes (10238.04 Kbytes)
        34.94% of uncompressed directory table size (30000940 bytes)
Number of duplicate files found 53005
Number of inodes 387822
Number of files 312876
Number of fragments 5541
Number of symbolic links  749
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 74197
Number of ids (unique uids + gids) 2
Number of uids 1
        william (1000)
Number of gids 2
        william (1000)
        plugdev (46)
```

#### Second Run

I `mv`ed the first image out of the way to netbook.squashfs2` (typo fixed) before running the below command:

```
time mksquashfs ../../../backup/HTS54501/ netbook.sqaushfs -b 1M -comp xz -Xdict-size 100%
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on netbook.sqaushfs, block size 1048576.
[===================================================================\] 334984/334984 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 1048576
        compressed data, compressed metadata, compressed fragments,
        compressed xattrs, compressed ids
        duplicates are removed
Filesystem size 23295520.88 Kbytes (22749.53 Mbytes)
        77.16% of uncompressed filesystem size (30191010.34 Kbytes)
Inode table size 3313992 bytes (3236.32 Kbytes)
        17.65% of uncompressed inode table size (18777754 bytes)
Directory table size 10483484 bytes (10237.78 Kbytes)
        34.94% of uncompressed directory table size (30001084 bytes)
Number of duplicate files found 53005
Number of inodes 387821
Number of files 312876
Number of fragments 5541
Number of symbolic links  748
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 74197
Number of ids (unique uids + gids) 2
Number of uids 1
        william (1000)
Number of gids 2
        william (1000)
        plugdev (46)

real    24m48.484s
user    187m17.196s
sys     0m56.495s
```

### Third Run

A few minutes after the second run, I ran `mksquashfs` a third time to get a third (differing!) set of numbers. I did not compare the tree to the first two runs using `rsync`, however.

```
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ time mksquashfs ../../../backup/HTS54501/ netbook.sqaushfs3 -b 1M -comp xz -Xdict-size 100%
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on netbook.sqaushfs3, block size 1048576.
[===================================================================\] 334984/334984 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 1048576
        compressed data, compressed metadata, compressed fragments,
        compressed xattrs, compressed ids
        duplicates are removed
Filesystem size 23295514.09 Kbytes (22749.53 Mbytes)
        77.16% of uncompressed filesystem size (30190986.55 Kbytes)
Inode table size 3308432 bytes (3230.89 Kbytes)
        17.64% of uncompressed inode table size (18758094 bytes)
Directory table size 10483576 bytes (10237.87 Kbytes)
        34.95% of uncompressed directory table size (29999248 bytes)
Number of duplicate files found 53005
Number of inodes 387463
Number of files 312876
Number of fragments 5541
Number of symbolic links  390
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 74197
Number of ids (unique uids + gids) 2
Number of uids 1
        william (1000)
Number of gids 2
        william (1000)
        plugdev (46)

real    24m43.850s
user    187m6.351s
sys     0m57.243s
```

#### True Symlink Total

```
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l | wc
    973     973   83757
```

Happy to provide other statistics of my filesystem if necessary; I'm not sure the correct `du` invocation to give information you need; the filesystem _is_ `30GB` according to `du`.

**Comment by plougher** [comment]
I get this issue raised a couple of times a year, and it is invariably due to wrong assumptions and/or testing on the behalf of the user.  That is they get different results between invocations of Mksquashfs, and then blame Mksquashfs.  But invariably the cause is the data has *changed* between invocations, and they are unaware of that fact.  Mksquashfs is not reproducible if the data has changed.

I do not know whether this is the case here, but, you have made the usual assumptions and made the usual mistakes in checking whether one filesystem is the same as another filesystem.

The following points are worth noting:

1. Mksquashfs 4.4 was released nearly 3 years ago, and the probability that such a gross bug (random failure to read symlinks) has not been discovered previously is extremely low.

2.  99 out of 100 cases where Mksquashfs produces different results is because the data has changed.   People erroneously tend to assume because *they* did not change the data, it didn't alter.  But, a typical Linux system has many processes and applications running which is constantly indexing and updating data.

3. In your case, you're assuming the 30 GB of data isn't changing.  But, you have provided no evidence to prove that is a fact.   Unless you can reproduce this on a "read-only" set of data, the mostly likely cause of the different results is because the data is changing.

4. Perhaps the most important point is your proof that image 1 and 2 are identical (despite different Mksquashfs output) is faulty, and it hasn't proved anything.

Symlink handling is notoriously difficult and variable between tools, and you have to be very careful when making comparisons between different directories (or filesystems), because how symlinks are handled can make the difference between an "identical" directory or a "non-identical" directory.  The most obvious case being whether the tool follows symlinks or not.

In your case, the use of rsync hasn't proved anything, because you've used the -a option which implies the -l (or --links) option.  The documentation for rsync gives the following definition

```
       -l, --links
              When symlinks are encountered, recreate the symlink on the destination.
```

In otherwords, rsync will always copy (recreate) symlinks into the destination, whether or not the symlink was already in the destination.  So, as a check to see if a symlink was missing in the destination it is completely useless, because the behaviour will be the same.

This is a worked example of that fact (with embedded comments):

```
phillip@linux:/tmp> ls -laR old
old:
total 12
drwxr-xr-x  2 phillip users 4096 Mar 31 06:45 .
drwxrwxrwt 73 root    root  4096 Mar 31 06:48 ..
-rw-r--r--  1 phillip users    6 Mar 31 06:02 hello
lrwxrwxrwx  1 phillip users    5 Mar 31 06:03 symlink -> hello

# old is a directory containing a file, and a symlink to that file.

phillip@linux:/tmp> cp -a old new

# We copy old to new, so we know that the two directories are identical.

phillip@linux:/tmp> rsync -aHphivn --compare-dest=../new old cmp
sending incremental file list
created directory cmp
cd+++++++++ old/
>f+++++++++ old/hello
cL+++++++++ old/symlink -> hello

sent 131 bytes  received 48 bytes  358.00 bytes/sec
total size is 11  speedup is 0.06 (DRY RUN)

# rsync insists on recreating the symlink even though it is already in the destination directory.

phillip@linux:/tmp> rm new/symlink

# We create a similar situation between the first Mksquashfs run which had 749 symlinks (old directory),
# and the second Mksquashfs run which had 748 symlinks (new directory), by deleting the
# symlink in new.

phillip@linux:/tmp> rsync -aHphivn --compare-dest=../new old cmp
sending incremental file list
created directory cmp
cd+++++++++ old/
>f+++++++++ old/hello
cL+++++++++ old/symlink -> hello

sent 131 bytes  received 48 bytes  358.00 bytes/sec
total size is 11  speedup is 0.06 (DRY RUN)

# The result is the same, because because rsync insists on recreating the symlink whether or not it already exists.
```

In otherwords, the "new" directory probably doesn't have a symlink which is in the "old" directory.    So it is utterly false to claim the above test shows the two directories to be identical.

So far I see no evidence that there is a bug in Mksquashfs.

What you should do in this situation, is one or more of the following.

1. Use tar or another archiving program, rather than mksquashfs.  If the same behaviour is experienced then it is obviously not a Mksquashfs bug. 

2. Run Mksquashfs against a directory hierarchy which is "read-only" and guaranteed not to change.  In that case the output should be reproducible.

**Comment by cr1901** [comment]
Before I close this and/or dig deeper:

I managed to create two images that are identical (**this was _not_ from a "read-only" filesystem**, it's going to be a bit of a pain to mount that drive read-only). The images only differ at 3 bytes ([modification time](https://dr-emann.github.io/squashfs/squashfs.html#_the_superblock)):

```sh
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ cmp -l netbook.squashfs netbook.squashfs2
          9 365   2
         10 162  16
         11 105 106
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$
```

These two images were created several hours apart with the following command lines:

## First Image

```sh
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ mksquashfs ../../../backup/HT$54501/ netbook.squashfs -b 1M -comp xz -Xdict-size 100%
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on netbook.squashfs, block size 1048576.
[===================================================================|] 334984/334984 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 1048576
        compressed data, compressed metadata, compressed fragments,
        compressed xattrs, compressed ids
        duplicates are removed
Filesystem size 23295514.09 Kbytes (22749.53 Mbytes)
        77.16% of uncompressed filesystem size (30190986.55 Kbytes)
Inode table size 3308432 bytes (3230.89 Kbytes)
        17.64% of uncompressed inode table size (18758094 bytes)
Directory table size 10483576 bytes (10237.87 Kbytes)
        34.95% of uncompressed directory table size (29999248 bytes)
Number of duplicate files found 53005
Number of inodes 387463
Number of files 312876
Number of fragments 5541
Number of symbolic links  390
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 74197
Number of ids (unique uids + gids) 2
Number of uids 1
        william (1000)
Number of gids 2
        william (1000)
        plugdev (46)
```

## Second Image (Several hours later)

```sh
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ mksquashfs ../../../backup/HTS54501/ netbook.squashfs2 -b 1M -comp xz -Xdict-size 100%
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on netbook.squashfs2, block size 1048576.
[===================================================================|] 334984/334984 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 1048576
        compressed data, compressed metadata, compressed fragments,
        compressed xattrs, compressed ids
        duplicates are removed
Filesystem size 23295514.09 Kbytes (22749.53 Mbytes)
        77.16% of uncompressed filesystem size (30190986.55 Kbytes)
Inode table size 3308432 bytes (3230.89 Kbytes)
        17.64% of uncompressed inode table size (18758094 bytes)
Directory table size 10483576 bytes (10237.87 Kbytes)
        34.95% of uncompressed directory table size (29999248 bytes)
Number of duplicate files found 53005
Number of inodes 387463
Number of files 312876
Number of fragments 5541
Number of symbolic links  390
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 74197
Number of ids (unique uids + gids) 2
Number of uids 1
        william (1000)
Number of gids 2
        william (1000)
        plugdev (46)
```

Notice the number of symbolic links found in both images- in fact, these two images appear to be identical to Third Run in my opening message!

## True Number Of Symlinks

The number of symlinks reported on from my source tree do not match what are reported by `mksquashfs`. However, the number of symlinks reported from the source tree _does_ match the number of symlinks from both images when mounted:

### Source Files

```sh
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l | wc
    973     973   83757
```

### SquashFS Images

```
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ sudo mount -o loop,ro netbook.squashfs old
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ sudo mount -o loop,ro netbook.squashfs2 new
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ cd old/
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook/old$ find -type l | wc
    973     973   83757
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook/old$ cd ..
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook$ cd new
william@xubuntu-dtrain:/shares/wjones/archive/work/netbook/new$ find -type l | wc
    973     973   83757
```

I don't know why `mksquashfs` decided not to report 583 of the symlinks, but all of them appear to have been copied properly to the image. **Would you consider this a stats reporting bug and worth exploring more?** I haven't dug deeper yet, such as:

1. Using a single CPU (this will take 7-8 times longer before I get results).
2. Mounting the source disk as read-only (probably mandatory to test a single CPU).
3. Compiling git HEAD of `squashfs-tools` and seeing if the issue disappeared.
4. Determining whether my `find` invocation matches how `mksquashfs` tallies up symlinks; `find` doesn't follow symlinks 
    without `-L`.
6. Figuring out why the uncompressed/compressed size changed between First, Second and Third Run.
    * One thing I forgot to mention in my original message was that despite having different statistics printed out, the 
      First/Second images had the same size in bytes (`ls -l` [block size is bytes](https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html)). They could've possibly been identical
      images as well save for modification time. but impossible for me to undelete them to check now :(. **The Third Run
      image size on disk was _not_ identical**.

**Comment by plougher** [comment]
You are *not* using Occam's Razor here, which is that the simplest explanation is the most likely.  When *I* discover a tool isn't working correctly, I first blame my understanding and methodology, and check it thoroughly.  Because it is always a more likely explanation than a bug in the tool.

Previously, I explained the most likely explanation for the changes in Mksquashfs output was that the input data was changing.   In otherwords it was your assumption that was false, and your methodology was false too.

Now, despite pointing that out, and  you obtaining 3 runs of identical data which tends to prove my explanation correct, you still insist on blaming the tool when *you* still have something you don't understand.  I not should have to spend my time fixing your knowledge, to show there is no bug in Mksquashfs.

Having made that criticism, I will now explain the most likely reason why Mksquashfs and Find give different results.  It is because you're comparing two different things (i.e. apples and pears) and expecting them to be the same.

Do you know the difference between a soft link (symbolic link), and a hard link?  You will need to understand this.

*****************
If not then a mini-tutorial.   Every file in the filesystem is represented by an inode.  The directory structure that you browse is an index, which contains a filename and a reference to an inode.   Normally there is *exactly* one filename for each inode.

Now sometimes you want to make a file that points to another file, aka as a link.   You can do this via a symbolic link or a hard link.  They're two different ways of achieving the same thing.

A symbolic link is itself an inode.   The contents of the inode *redirects* you to the linked file by giving a pathname which must be followed.

A hard link is simply another filename entry in the index, which points to an already created inode - this is the inode of the file you're linking to.
*******************
 
The problem with symbolic links and hard links is the *directory structure* looks identical whether a symbolic link or hard link is being used.   But they are subtly different which causes issues occasionally.  One difference is in the *inode* count.  People naively assume the number of files in a directory structure is the same as the number of inodes.  This is true for symbolic links, but, it is not true for hard links.

This manifests itself in the use of programs like FIND to count the number of inodes.  Find doesn't follow symbolic links, but, it does follow hard links.  That is FIND will return the list of files in a directory structure including what may be multiple references to the same inode.

So, if you have 100 hard links in a directory, "find xxx | wc" will over-count the number of inodes by 100.

This is the most likely explanation for the difference here.   Find is counting *973* symbolic links.   But this includes *583* hard links to symbolic links.  This is your "apples" result.

Mksquashfs reports the number of symbolic link inodes created in the filesystem or *390* symbolic links.  This does not include hard links.  This is your "pears" result.

So, there is no bug here in Mksquashfs, just a misunderstanding that "find -type l | wc" counts inodes.

This is a worked example to show the differences.

```
phillip@linux:/tmp> mkdir test
phillip@linux:/tmp> cd test
phillip@linux:/tmp/test> touch file

# Create a symlink to file.  The symbolic link is an inode in the
# filesystem.

phillip@linux:/tmp/test> ln -s file symlink

# Create a hardlink to symlink.  Hardlinks are just another
# reference to an existing inode.

phillip@linux:/tmp/test> ln symlink hardlink

# We can show this by stating hardlink and symlink.  They both reference
# the same inode.  The number of references to the inode is also 2.

phillip@linux:/tmp/test> stat hardlink
  File: hardlink -> file
  Size: 4               Blocks: 0          IO Block: 4096   symbolic link
Device: 832h/2098d      Inode: 1578705     Links: 2
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/ phillip)   Gid: (  100/   users)
Access: 2022-04-04 09:08:21.068788161 +0100
Modify: 2022-04-04 09:08:21.068788161 +0100
Change: 2022-04-04 09:08:27.316222741 +0100
 Birth: 2022-04-04 09:08:21.068788161 +0100
phillip@linux:/tmp/test> stat symlink
  File: symlink -> file
  Size: 4               Blocks: 0          IO Block: 4096   symbolic link
Device: 832h/2098d      Inode: 1578705     Links: 2
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/ phillip)   Gid: (  100/   users)
Access: 2022-04-04 09:08:43.226782744 +0100
Modify: 2022-04-04 09:08:21.068788161 +0100
Change: 2022-04-04 09:08:27.316222741 +0100
 Birth: 2022-04-04 09:08:21.068788161 +0100
phillip@linux:/tmp/test> cd ..

# Create a Squashfs filesystem from test.  The Mksquashfs
# summary is the number of inodes created, and so there
# should be 1 symlink inode.

phillip@linux:/tmp> mksquashfs test test.sqsh
Could not open regular file for writing as destination: Permission denied
phillip@linux:/tmp> mksquashfs test test.sqsh
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on test.sqsh, block size 131072.
[|                                                                                                                                                               ] 0/0 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
        compressed data, compressed metadata, compressed fragments,
        compressed xattrs, compressed ids
        duplicates are removed
Filesystem size 0.25 Kbytes (0.00 Mbytes)
        85.42% of uncompressed filesystem size (0.29 Kbytes)
Inode table size 65 bytes (0.06 Kbytes)
        69.15% of uncompressed inode table size (94 bytes)
Directory table size 47 bytes (0.05 Kbytes)
        82.46% of uncompressed directory table size (57 bytes)
Number of duplicate files found 1
Number of inodes 3
Number of files 1
Number of fragments 0
Number of symbolic links 1
          ^^^^^^^^^^^^^^^^
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 1
Number of hard-links 1
Number of ids (unique uids + gids) 2
Number of uids 1
        phillip (1000)
Number of gids 1
        users (100)
phillip@linux:/tmp> sudo mount -t squashfs test.sqsh /mnt
[sudo] password for root:

# Use find to list the symlink inodes.  But find prints *each*
# reference to the symlink, which is not the same as the number
# of inodes, if hardlinks are present.

phillip@linux:/tmp> find test -type l
test/hardlink
test/symlink
phillip@linux:/tmp> find /mnt -type l
/mnt/hardlink
/mnt/symlink
```

**Comment by cr1901** [comment]
You are correct:

```
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l -links 1 | wc
     31      31    2376
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l -links 2 | wc
    502     502   48148
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l -links 3 | wc
    129     129   10176
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l -links 4 | wc
    164     164   13496
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l -links 5 | wc
      0       0       0
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l -links 6 | wc
    138     138    8886
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l -links 7 | wc
      0       0       0
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l -links 8 | wc
      0       0       0
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$ find . -type l -links 9 | wc
      9       9     675
william@xubuntu-dtrain:/shares/wjones/backup/HTS54501$
```

`31 + 502/2 + 129/3 + 164/4 + 138/6 + 9/9 = 390`, which matches the results `mksquashfs` returns.

Whatever is creating symlinks in the tree (First/Second Run) is not updating any `mtime` metadata (this tree hasn't been touched _by me_ since 2018), so the only way I'm going to figure out for sure is to catch the process doing the update in the act; I know Ubuntu runs a disk scanning service every day to quickly index directories, probably a decent hint. I'll figure it out later.

Thank you for the explanations and examples, and sorry for not doing my due diligence.

**Comment by plougher** [comment]
Thanks for the feedback, and I'm glad everything worked out in the end.
