### ISSUE TITLE
sqfstar rejects compression options that require a parameter

### ISSUE THREAD

**Issue by jjr-simiatec** [plougher/squashfs-tools#191]
Example command lines as follows:
```
$ sqfstar -comp xz -Xbcj arm,x86 test.sqfs < test.tar
xz: -Xbcj missing filter
$ sqfstar -Xcompression-level 5 test.sqfs < test.tar
gzip: -Xcompression-level missing compression level
gzip: -Xcompression-level it should be 1 >= n <= 9
$ sqfstar -comp zstd -Xcompression-level 15 test.sqfs < test.tar
zstd: -Xcompression-level missing compression level
zstd: -Xcompression-level it should be 1 <= n <= 22
```
The problem would seem to be in function `sqfstar()` in [`mksquashfs.c`](https://github.com/plougher/squashfs-tools/blob/62a8a93f84b169955054dc086e5024ef4895ad17/squashfs-tools/mksquashfs.c#L6422).

**Comment by plougher** [comment]
Before the fix is in a release version, you can use the equivalent -tar option to mksquashfs, i.e. your three examples can be replaced with:

$ mksquashfs - test.sqfs -tar -comp xz -Xbcj arm,x86 < test.tar

$ mksquashfs - test.sqfs -tar -Xcompression-level 5 < test.tar

$ mksquashfs - test.sqfs -tar -comp zstd -Xcompression-level 15 < test.tar
