### ISSUE TITLE
Need dictionary for error signals.

### ISSUE THREAD

**Issue by ralmond** [plougher/squashfs-tools#207]
I'm having problems using the Pop_OS installer on a Surface Pro 3.

The installer logs gives me the following error:
```
[INFO distinst:src/installer/mod.rs:413] Extracting /cdrom/casper_pop-os_22.04_amd64_nvidia_debug_199/filesystem.squashfs
[DEBUG distinst:crates/squashfs/src/lib.rs:166] "unsquashfs" "-f" "-d" "/tmp/distinst.azNU4SbhtSDC" "/cdrom/casper_pop-os_22.04_amd64_nvidia_debug_199/filesystem.squashfs"
[ERROR distinst:src/installer/state.rs:37] extracting error: archive extraction failed with status: signal: 9
[ERROR distinst:src/installer/mod.rs:300] errored while installing system: archive extraction failed with status: signal: 9
[INFO distinst:ffi/src/installer.rs:190] Install error: archive extraction failed with status: signal: 9
```

The problem is that I have no idea what `status: signal: 9` is (or for that matter `status: signal: xx`.  It would be really nice to have a key where I could look that up and possibly find more information about my problem.

**Comment by Dr-Emann** [comment]
https://dsa.cs.tsinghua.edu.cn/oj/static/unix_signal.html

**Comment by plougher** [comment]
This is reported by the installer program when it detects Unsquashfs has been killed with signal 9.

As such it is the installer program which is responsible for the error message and has given the above "obscure" error.

There is nothing that Unsquashfs can do here because signal 9 is the SIGKILL signal which means Unsquashfs dies immediately without the opportunity to do anything.

This issue should be addressed by Pop_OS.   But the probable reason is your system has run out of memory.
