### ISSUE TITLE
Feature request: Quickly abort compression on incompressible blocks

### ISSUE THREAD

**Issue by wychen** [plougher/squashfs-tools#240]
Some files are incompressible because they are already compressed, like many archiving containers and multimedia files. mksquashfs already save the original content if the compressed size is larger than the original data, but it might be a bit wasteful if the compression is slow. If we can quickly determine a block is hard to compress, then we can early abort the compression and directly save the original data.

One very easy way to proceed is to use zstd level 1 to see if the block is compressible. It's very fast so the cost of doing so is low. However, this is most suitable if the real compression is also zstd. If we are using zstd level 1 as a quick test for say xz, the current architecture needs to change a bit. This would also make the early abort feature depend on zstd.

Decisions:
* Should we introduce a command line flag? Yes, because even if it's unlikely that a block not compressible by zstd level 1 can be compressed well by other compressor, and that the CPU cost of doing this is low, users might still not want the overhead and slightly larger file size.
* Should we make this a zstd-only feature? If we do, we'd only touch `zstd_compress()`. If not, the availability of this feature would depend on whether zstd is supported. In that case, we can modify `mangle2()` to add a `ZSTD_compressCCtx()` call wrapped by build flag `ZSTD_SUPPORT`. Which one do you prefer?

**Comment by wychen** [comment]
I'm happy to polish my prototype and send a PR, but I'd like to make sure this feature aligns with the direction of this project.

**Comment by plougher** [comment]
There is already support in Mksquashfs to tell it not to compress files.  It is called the uncompressed() action.

See https://github.com/plougher/squashfs-tools/blob/master/ACTIONS-README

Specifically the uncompressed() action

```
 5.2.7 uncompressed()
--------------------

Tell Mksquashfs to not compress the files matching the expression.

This action obviously can be used to avoid compressing already compressed
files (XZ, GZIP etc.).
```

The test expression can be a name match such as -name(*.jpg), which will match on any file ending in *.jpg.

```
mksquashfs xxx xxx.sqsh -action "uncompressed@name(*.jpg)"
```

Will make Mksquashfs not try to compress any JPEG file.

In cases where the file name is insufficient to determine if it should be compressed, the file() test can be used.

```
mksquashfs xxx xxx.sqsh -action "uncompressed@file(compressed)"
```

This will tell Mksquashfs not to compress any file that the file command reports as already compressed.

Obviously the above can be combined, and can be combined with any of the other Action tests to determine if a file should be uncompressed.

Matching on name or file content is a much more efficient way of doing this, and it is the use-case that people want.

If you _really_ want to try and compress a file to determine if it is worth Mksquashfs compressing it, _you_ can write an external script or program and execute _that_ returning whether Mksquashfs should compress it.

The exec() test will execute a script which can do any testing you like on the said file, for example

```
mksquashfs xxx xxxx.sqsh -action"uncompressed@exec(compressible.sh)
```

Where compressible.sh is your script or program which experimentally compresses the first one or more blocks and returns failure (non-zero exit code) if the resultant blocks are too large, or if it takes too long to compress.

Your script or program is passed the following environment variables.

```
                /*
                 * Create environment variables
                 * NAME: name of file
                 * PATHNAME: pathname of file relative to squashfs root
                 * SOURCE_PATHNAME: the pathname of the file in the source
                 *                  directory
```

In other words there are better ways to do what you're doing,  and Mksquashfs already supports it.

It is not the job of Mksquashfs to decide if a file is worth compressing (beyond the obvious of being larger once compressed).

The reason for _that_ should be obvious.   One man's meat is another man's poison.   What one person thinks is a worthwhile time spent on getting a 5% reduction in size  is another's waste of computation where that file should have been treated as uncompressed.

As such Mksquashfs can't and won't get into the business of implementing your use-case because it is far too specific and not generic.

As I said above, Mksquashfs instead implements the actions mechanism which allows _you_ to determine if a file should be uncompressed using  tests, including the exec() test which allows any policy to be chosen.  This is the reason why Actions were implemented.
 
So what you ask is already implemented in a better way.

**Comment by wychen** [comment]
Thank you for your prompt response and thorough explanation of the existing functionality in Mksquashfs. The actions mechanism and the `uncompressed()` action are indeed powerful and versatile tools for managing file compression in a variety of use-cases. I appreciate your attention to the needs of the user community.

While I understand that the file-based approach using actions is fast and effective for many scenarios, I would like to respectfully suggest that a block-based approach could be more accurate in many cases. Specifically, files that contain mixed compressibility resources, such as PDFs with both text (compressible) and JPEG images (not compressible), or uncompressed tar or VM images containing various kinds of files, may benefit from a more granular approach.

Other than better accuracy, using zstd with level=1 as a quick test for block compressibility is faster than the `file()` and `exec()` tests, providing a more efficient means of determining data should be compressed or not.

I understand your point that what one person considers a worthwhile time spent on achieving a 5% reduction in size may be another person's waste of computation. However, I believe that the low-cost block-based early abort approach could offer the best of both worlds. By focusing computation on compressible blocks, it would strike a better balance between compression efficiency and computational cost. For example, if a user employs the default gzip level 9, quick test using zstd level 1 introduces less than 5% computational overhead. Therefore, if their source files contain more than 5% of incompressible blocks, this approach would yield a net gain. I understand not all the datasets contain more than 5% of incompressible blocks, so only enable this with a command line option makes more sense.

My intention is not to undermine the existing functionality of Mksquashfs but rather to propose a way to make the existing mechanism more efficient. Mksquashfs already keeps the original data if the compressed data becomes larger. This proposal just makes this decision faster by adding a quick entropy test. I understand that implementing such a feature may not align with the project's current direction, and I respect your decision on this matter.

However, if you are open to considering this approach or discussing it further, I would be more than happy to share my thoughts and collaborate on potential solutions. I believe that integrating the low-cost block-based early abort technique could enhance Mksquashfs' compression efficiency and provide additional value to users who are looking for better compression without significant computational overhead.

Thank you for your time and consideration. I appreciate the opportunity to engage in this discussion and look forward to hearing your thoughts on this proposal.
