### ISSUE TITLE
Does mksquashfs 4.6.1 support generating squashfs 2.0 systems?

### ISSUE THREAD

**Issue by motogodfather** [plougher/squashfs-tools#272]
Since some old Motorola cell phone firmware uses squashfs2.1 file system, I wonder if mksquashfs 4.6.1 can support to generate squashfs2.1 image file?

**Comment by plougher** [comment]
No, Mksquashfs 4.6.1 cannot generate v2.1 filesystems as they're obsolete (and have been since about 2006).

The last release of Squashfs-tools that can generate v2.1 filesystems is squashfs2.2-r2 released in 2005.  This is available on Sourceforge here https://sourceforge.net/projects/squashfs/files/squashfs/squashfs2.2-r2/

Unfortunately because that release is 18 years old, the code no longer compiles on modern Linux distributions (Debian, Ubuntu etc).

If you are able and happy to build Squashfs-tools from source, I will be prepared to update the squashfs2.2-r2 source code so that it can be built on a modern Linux distribution, and I will either attach the updated tarball here, or a patch to the tarball on Sourceforge.

Please say whether you're able to download and build the source code from scratch, and apply a patch.

**Comment by plougher** [comment]
I have attached a zip file of the updated squashfs2.2-r2 release source code, and a patch file against the tarball on Sourceforge (https://sourceforge.net/projects/squashfs/files/squashfs/squashfs2.2-r2/)

Please let me know if you help in compiling it etc.

[squashfs-tools.zip](https://github.com/plougher/squashfs-tools/files/13628161/squashfs-tools.zip)
[update.patch](https://github.com/plougher/squashfs-tools/files/13628142/update.patch)

**Comment by motogodfather** [comment]
> I have attached a zip file of the updated squashfs2.2-r2 release source code, and a patch file against the tarball on Sourceforge (https://sourceforge.net/projects/squashfs/files/squashfs/squashfs2.2-r2/)
> 
> Please let me know if you need help in compiling it etc.
> 
> [squashfs-tools.zip](https://github.com/plougher/squashfs-tools/files/13628161/squashfs-tools.zip) [update.patch](https://github.com/plougher/squashfs-tools/files/13628142/update.patch)

The mksquashfs file can be built from the source code you provided (build environment: 6.2.0-37-generic #38~22.04.1-Ubuntu)
Can you provide the unsquashfs source code for squashfs2.1 as well?

**Comment by plougher** [comment]
Unsquashfs did not exist in Squashfs 2.x.  But any Unsquashfs from 2007 onwards, such as Unsquashfs 4.5 etc. supports reading Squashfs 2.x filesystems.
