### ISSUE TITLE
Fakeroot with Mksquashfs doesn't work with extended capabilities

### ISSUE THREAD

**Issue by GabrielGhe** [plougher/squashfs-tools#44]
I'm building several fairly large squashfs in parallel (500mb+) and I'm using mksquashfs with fakeroot to copy over the extended capabilities.
http://man7.org/linux/man-pages/man7/xattr.7.html

The uids and gids get copied over properly every time, but some extended attributes fail to get copied over to the squashfs.

I'm not sure what else to try. It's either a problem with mksquashfs or fakeroot.

Problem: intermittently fails to copy over xattrs when using mksquashfs.

It may be related to https://bugs.busybox.net/show_bug.cgi?id=10141
I tried applying the patch from the link above. It didn't help.

**Comment by plougher** [comment]
Mksquashfs simply executes the system calls via the library wrappers.  It has no knowledge of the uid/privilege level of the user running it, and it doesn't really care, as that's handled by the system calls.  If the user doesn't have the right privilege, the system calls will produce an error.

In other words it is the fakeroot package (which uses LD_PRELOAD to load the libfakeroot.so
wrapper around the system calls) that allows a non-privileged user running Mksquashfs to do privileged operations.

If Mksquashfs fails it is because something in the fakeroot wrapper has failed to fake the privileges.  So this is obviously a bug in the fakeroot package, and nothing to do with Mksquashfs.

Mksquashfs may be triggering a bug in fakeroot, due to parallelism (as suggested in the linked bug report).  You could try reducing the number of threads used by Mksquashfs with the -processors option.

Closing as this isn't a bug in Mksquashfs.
