### ISSUE TITLE
Possibility of a new release?

### ISSUE THREAD

**Issue by blake-riley** [plougher/squashfs-tools#54]
Firstly, thanks for all your work developing squashfs!
With the recent addition of zstd support into this code, I was wondering if you had considered creating a new release?

I just put in a pull request to [add this feature to squashfs on Homebrew](https://github.com/Homebrew/homebrew-core/pull/32818) (a MacOS package manager), but they'll only consider "stable releases"---which for squashfs-tools is from quite a while ago.

**Comment by plougher** [comment]
Yeah, I'll probably try and find time to do another release over the next
few months (probably my Christmas vacation).

Over the last couple of years I have become very busy  with my main job
(Redhat kernel maintainer).  This year has been exceptionally bad dealing
with the fallout of Omega (Meltdown/Spectre).

Phillip

**Comment by alphaonex86** [comment]
I need zstd too

**Comment by mvo5** [comment]
I understand that things are very busy, I wonder if there is anything we can do to help you (@plougher) to make it easier for you to release?

**Comment by hunger** [comment]
I would also welcome a new release very much!

**Comment by lucab** [comment]
An upstream release would also mitigate the pressure of downstream distributions trying to cherry-pick specific patches (see https://bugzilla.redhat.com/show_bug.cgi?id=1648490).

**Comment by plougher** [comment]
Well I didn't get time to do a new release over the Christmas period.

This is because my Father had a stroke and was in hospital for over a week over Christmas.

I have not had *any* vacation since Christmas either.

**Comment by plougher** [comment]
I see if I have some hours this week to do a bare-bones quick release.

**Comment by plougher** [comment]
First round of adding reproducible builds, and fixing a couple of reported bugs has been done.  This, as usual, has taken longer than expected.

I still have some necessary options to add to finish reproducible builds (no mkfs timestamps, and other timestamps).

But, a release should be done this week.

**Comment by plougher** [comment]
Well this release has taken longer than I hoped.  But you should see from the commit log that I have been busy addressing the backlog of issues and pull requests.  Having done so should make this a better release, as I have fixed and addressed as many issues as possible.

The two CVEs (CVE-2015-4645 & CVE-2015-4646) took sometime to fix properly, as I always expected they would.   Over seven commits to fix over a two week period (with other fixes).   Adding sanity checks to make the code more robust are always tricky, because you have to make absolutely certain there are not circumstances where you reject valid file systems.  As in the case here, to get the information to do this reliably often requires restructuring of the code.  So the difficulties in addressing it properly quickly explode.

**Comment by jtligon** [comment]
apologies! we appear to be good with what we have in fedora! IGNORE ME!

**Comment by plougher** [comment]
I have just released Squashfs tools 4.4 :-)  Thanks for your patience it took longer and much more effort than I expected.

The release tarball is available in two places:

1. The traditional tarball on Sourceforge.  See [here](http://sourceforge.net/project/showfiles.php?group_id=63835)

2. The tarball snapshot of the GitHub git repository generated from the release 4.4 tag [here](https://github.com/plougher/squashfs-tools/archive/4.4.tar.gz)

The two tarballs are essentially the same, but, the Sourceforge tarball being a custom tarball (rather than a repository snapshot), has a lot of the old stuff in the repository removed (kernel patches, old READMEs)

**Comment by CvH** [comment]
@plougher you can add any files you want to an gh release too, there is no need to ship different versions. Btw tx!

**Comment by plougher** [comment]
Do you have a link to the documentation, because that will be useful for
next time.  Thanks. Regards

**Comment by CvH** [comment]
https://github.com/plougher/squashfs-tools/releases/new
![image](https://user-images.githubusercontent.com/1355173/64031067-00062f80-cb48-11e9-89cb-7cba74328890.png)

btw you can also edit your already made releases and add an binary etc :)
