### ISSUE TITLE
Memory Limit not respected

### ISSUE THREAD

**Issue by pmikka** [plougher/squashfs-tools#60]
Hi,
I'm trying to create a large squashfs image on Debian 8 and I hope you can help me with my problem.

I tried the following mksquashfs versions: 4.2+20130409-2, 4.3-3+deb9u1, 4.3 from sourceforge and 4.3 (6e242dc) from here. With all of them I'm facing the same issue: all the available memory is used by mksquashfs, even though I set the "-mem=4G" option.

I'm trying to create a mountable squash filesystem from an old backup-drive. It contains many backups created by backintime (basically rsync + cp -l). The reason to transform this is, I would like to have a easily mountable, compressed copy to write on my fileserver, so that I can destroy the harddrive.

The filesystem in question (sourcefs), is an xfs with 415G of used space and 55M of inodes. My machine is an core i7-4771 with 16GB of RAM.

When I'm running mksquashfs it does not seem to come to an end. It basically just consumes all the available memory. E.g. one ps aux output:
_root      5027 43.9 56.1 10319440 **9213632** pts/0 Rl+ 18:10   8:27 mksquashfs /sourcefs /exportedfs/destfile.sqsh -processors 1 -force-uid 1000 -force-gid 1000 -mem 4G -info -progress -no-exports_

After ~8 minutes of CPU time mksquashfs already consumer 9G of RAM. CPU load is <100% on one core. If I wait longer, swapping starts and cpu load is heavily decreased. The exportedfs is NTFS. Filesize even after >30 Minutes of runtime is 0 bytes. The complete output from mksquashfs is:
_Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /exportedfs/destfile.sqsh, block size 131072._

**Comment by pmikka** [comment]
Hi,
I'm trying to create a large squashfs image on Debian 8 and I hope you can help me with my problem.

I tried the following mksquashfs versions: 4.2+20130409-2, 4.3-3+deb9u1, 4.3 from sourceforge and 4.3 (6e242dc) from here. With all of them I'm facing the same issue: all the available memory is used by mksquashfs, even though I set the "-mem=4G" option.

I'm trying to create a mountable squash filesystem from an old backup-drive. It contains many backups created by backintime (basically rsync + cp -l). The reason to transform this is, I would like to have a easily mountable, compressed copy to write on my fileserver, so that I can destroy the harddrive.

The filesystem in question (sourcefs), is an ext4 with 415G of used space and 55M of inodes. My machine is an core i7-4771 with 16GB of RAM.

When I'm running mksquashfs it does not seem to come to an end. It basically just consumes all the available memory. E.g. one ps aux output:
_root      5027 43.9 56.1 10319440 **9213632** pts/0 Rl+ 18:10   8:27 mksquashfs /sourcefs /exportedfs/destfile.sqsh -processors 1 -force-uid 1000 -force-gid 1000 -mem 4G -info -progress -no-exports_

After ~8 minutes of CPU time mksquashfs already consumer 9G of RAM. CPU load is <100% on one core. If I wait longer, swapping starts and cpu load is heavily decreased. The exportedfs is NTFS. Filesize even after >30 Minutes of runtime is 0 bytes. The complete output from mksquashfs is:
_Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /exportedfs/destfile.sqsh, block size 131072._

**Comment by pacho2** [comment]
Dropping 0016-remove-frag_deflator_thread.patch and 0017-add-zstd-support.patch from Debian patchset stops the memory leak

**Comment by pacho2** [comment]
The real culprit is only 0016-remove-frag_deflator_thread.patch

**Comment by plougher** [comment]
Is this that piece of rubbish?

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwiIpMjnrYzhAhWVoXEKHSM3B94QFjAAegQIAhAB&url=https%3A%2F%2Fbugs.debian.org%2Fcgi-bin%2Fbugreport.cgi%3Fatt%3D1%3Bbug%3D919207%3Bfilename%3D0016-remove-frag_deflator_thread.patch%3Bmsg%3D24&usg=AOvVaw0EmPWZdGm1kergUjSyBGyP

I cannot believe Debian put that into their distribution because it is complete and utter crap.

**Comment by plougher** [comment]
It additionally means Mksquashfs on every Debian system is utterly broken.  Idiots.

What that piece of shit masquerading as a patch does is to *remove* the fragment compressor thread?

Now what you do you think happens then?  The fragments are not compressed while Mksquashfs is running (and written to disk), and just pile up in memory.  No wonder there's a huge memory leak.

Sorry, not my fault.  It is not my code.

I can't stop maintainers and others from being fuckwits.

**Comment by pmikka** [comment]
Thank you for the feedback, but I have still one doubt.
I was also trying the latest sourceforge and git version (6e242dc). Both showed the same result. While the patch might make it worse, it does not seem to be the only issue here.

**Comment by plougher** [comment]
Yeah, that's probably easy to explain too.  Depends on how much you understand how programs work.  If you've dug into the patches that Debian have applied then you probably do understand.

In the previous releases of Mksquashfs I exposed the internal buffering scheme to users.   That is I allowed users to decide how much memory they wanted to give to A, to B, to C etc.

In the case of Mksquashfs, as it uses parallel processing extensively, to get best performance it has to use buffers, caches and queues between producer processes and consumer processes to allow producer processes to work ahead of consumer processes.    This produces a pipeline of processes from input-reader(s) -> compressors -> output-writers.  Each with  queue(s) and with multiple buffer caches (for fragments, blocks etc).

The As Bs and Cs thus exposed to the user  was how much buffer space for X buffer, Y queue etc.

In fact this was information overload.  Most people didn't understand what this meant and didn't alter the defaults.  But, some people thought they understood what they meant, and then choose values which throttled Mksquashfs, making it perform  worse than the conservative defaults.

So the options at best were useless and at worst dangerous.

In this release of Mksquashfs, I went the opposite way.  I collected all those options up into one big option called -mem.   Users can give a size in Kbytes, Mbytes or Gbytes, and the program will internally split it up between buffers/caches/queues in the known best way for maximum performance.

Normal users should now not be scared to alter the memory size (as it is presented in an easy to understand way), and "power" users can't set the values in a way that produces poor performance.

It was also deliberately just called "-mem" rather than say "-buffer-mem" to keep it easy to understand.

But, it only controls the amount of memory Mksquashfs uses for it's internal read/write buffers.  It does not limit the amount of memory Mksquashfs uses overall.

Mksquashfs needs to scan the filesystem and read the metadata (inodes, directory names etc.)  and then cache that in memory.  It also needs to cache the compressed metadata (inode table and directory table) because that is only written to the Squashfs filesystem after data blocks.

If you have a very big filesystem, or one with many small files (i.e. low ratio between data and metadata), it may mean Mksquashfs will end up caching 2, 3, 4 Gigabytes of metadata or more, ontop of the -mem value.  It entirely depends on the filesystem.

This memory is not controlled by the -mem option.

**Comment by plougher** [comment]
I was also rather annoyed yesterday when I discovered it was *that* patch causing the problems.

That patch has been floating about for a number of years in various forms.

It has caused immense problems when people have applied it, because it doesn't work.  It breaks Mksquashfs.   But it only breaks it "fairly" subtly, when Mksquashfs is under memory or I/O load.

As Mksquashfs is not performing correctly they complain to me.   I have then often spent hours tracking down the problem only to discover *that* patch has been applied.

It not only wastes my time, but it also makes people think Mksquashfs is buggy and unreliable.

**Comment by pacho2** [comment]
Thanks a lot for the explanation :)

Do you think it would be feasible to do a new release? I think that could help downstreams to stop picking random patches from different resources, otherwise, I think that this could reappear in the future as they will keep applying "fixes" downstream 
Thanks

**Comment by pmikka** [comment]
Thank you for the explanation.

To sum it up: The filesystem I was trying to store inside a squashfs cannot be done on my 16GB RAM + 16GB swap machine. Even though I already tried to limit the RAM consumption by processors, mem and no-exports. 
No further option might help, no upstream change is available. Correct?

**Comment by plougher** [comment]
You say " xfs with 415G of used space and 55M of inodes."

Something is very wrong here.

Here's the basic facts about what Msquashfs does.  It scans the source filesystem and it builds an in-memory directory tree of the source filesystem.  This includes every inode in the filesystem, and every filename.

Now, how much inode and filename data does your filesystem have?  Even with 55M inodes I don't see how this can blow up to 16GB+16GB.

Say each of your 55M inodes takes 50 bytes for the inode, and 50 bytes for the filename, which represents 5.5 GB.

So, either you have much more metadata than you say, or you have a memory leak.

The first is easy to check.  How many files do you have, and what is the size of the filenames.  Do the matfs, what is the total size of the inodes and filenames.  ls  -R | wc will give an estimate for the memory required to store all the filenames.

If this does not add up to 16GB+16GB, then I suspect a memory leak.  Either there is something wrong with your Mksquashfs, or a problem elsewhere.

Let's be blunt there, I suspect you have a broken Mksquashfs, and/or system, or you're not being fully honest about the size of your filesystem metadata.

I want you to be using a vanilla Mksquashfs, I want some more facts about your filesystem, and I want more willingness to track down the problem from you.  Mksquashfs doesn't seem to be working for you, but it seems to be working for everyone else.    What is special about your setup or your filesystem.  I don't have a crystal ball here, and with no more information, there is nothing more I can do.

**Comment by plougher** [comment]
Closing this because no more information necessary to investigate it has been provided.
