### ISSUE TITLE
unsquashfs gets stuck (hangs) if destination filesystem does not support extended attributes

### ISSUE THREAD

**Issue by n0-1** [plougher/squashfs-tools#91]
Hi,

Trying to extract an image containing xattrs into a filesystem which doesn't support them causes set_attributes() called from writer() to return FALSE and the caller then sets 'failed = TRUE'. But since this variable is not reset anymore, the whole pipeline eventually comes to a halt. If '-no-xattrs' is passed to unsquashfs, the problem does not appear.

I identified commit baf779df67f97 ("unsquashfs: writer: Fix propagation of failure status") to be the culprit, please revert it. Since writer() does not return and 'failed' is a local variable, the change doesn't do what its commit message promises, anyway.

Cheers, Phil

**Comment by plougher** [comment]
The error status of the "failed" variable is returned via the queue write on line unsquashfs.c:2072

 queue_put(from_writer, (void *) failed); 

But you're right in that this wasn't the way to fix the propagation of the failure status, because it results in the failed variable not being reset.

This issue is properly fixed in the commit https://github.com/plougher/squashfs-tools/commit/3051a91b9b44c47f1ca895a697c06cddd18f97a9
