### ISSUE TITLE
SQUASHFS error: xz decompression failed, data probably corrupt

### ISSUE THREAD

**Issue by ohmyandy** [plougher/squashfs-tools#95]
Hi there,

Occasionally I see the following error messages when booting:

SQUASHFS error: xz decompression failed, data probably corrupt
SQUASHFS error: squashfs_read_data failed to read block 0x2dba2
SQUASHFS error: Unable to read fragment cache entry [2dba2]
SQUASHFS error: Unable to read page, block 2dba2, size 14400
SQUASHFS error: Unable to read fragment cache entry [2dba2]
SQUASHFS error: Unable to read page, block 2dba2, size 14400

Only HW reset helps, and after the reset the messages are gone, and the board boots as expected.
If the data was corrupt I guess HW reset would not help.
On the board is NOR flash, so I guess it is not related to bad blocks.
Has anyone seen this issue before?
Maybe it has already been fixed in the newer Linux kernel?

Linux kernel 4.14

Cheers,
Andy

**Comment by plougher** [comment]
There are no reported issues with kernel 4.14 or earlier.

The above errors will be produced if the data on the flash is corrupted.  But they will occur if some hardware hasn't be initialized properly, there is a bug in a low level driver, or memory is unreliable.

Basically anything that may lead to data corruption between reading the flash and presentment to Squashfs could be the culprit.  Any of these failures can "go away" with a HW reset.

As there are no reports of Squashfs issues in kernel 4.14 this is most likely caused by a failure elsewhere.
