### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by haampie** [plougher/squashfs-tools#96]
Can we get a new release?

Not having https://github.com/plougher/squashfs-tools/commit/fe2f5da4b0f8994169c53e84b7cb8a0feefc97b5 is quite a nuisance.

**Comment by dvzrv** [comment]
@plougher it would be awesome to see more activity in this repository. There are open pull requests dating back to 2017 for various fixes, such as cross platform support, selinux support, etc.

If you do not have the time to maintain this project anymore, maybe you can ask around here and find collaborators to take care of more of the process?
You can even move this repository to a github organization, if feasible.

**Comment by plougher** [comment]
> @plougher it would be awesome to see more activity in this repository. There are open pull requests dating back to 2017 for various fixes, such as cross platform support, selinux support, etc.
> 

That comment is somewhat disingenuous.  The last release was "29 Aug 2019", 6 of the outstanding pull requests are after that date, with 5 before, and 39 closed.  So that means there were 5 remaining pull requests outstanding at my last release, or 5 out of a total of 44 at that point, or 89% dealt with.

The remaining 5 pull requests were not pulled due to a "lack of maintenance" which is your unsubstantiated claim.   I did not pull them at the time of the last release because they did not meet my criteria for acceptance.    Any additional options added (via pull requests) must be seen to be genuinely useful to a reasonable percentage of the user base, and not be in effect "a one off" fix for a single person because of a particular problem they may have.  That is an unreasonable basis for inclusion especially if there is an alternative way of doing it which does not need an extra option.

Mksquashfs already has too many options, which can be confusing to people.  I do not wish Mksquashfs to be become a "Swiss Army knife" of ad-hoc options that fix issues that very few people need, and can be fixed elsewhere.

As to why I have left these 5 pull requests open, that is a courtesy to you the users.   Being still open they are visible on the pull-requests page, and so are available for anyone to comment that they'd like that option too.   Which may shift the criteria for their inclusion in a new release.  A closed pull-request is not visible.

If open pull-requests from a couple of years ago are giving the false impression that the project is un-maintained then I'll switch to a policy of closing any request I do not agree with instantly.

> If you do not have the time to maintain this project anymore, maybe you can ask around here and find collaborators to take care of more of the process?

I find this comment very offensive.  It is you that has gathered a false impression here.   Open requests do not mean unreviewed requests.


> You can even move this repository to a github organization, if feasible.

**Comment by dvzrv** [comment]
> I find this comment very offensive. It is you that has gathered a false impression here. Open requests do not mean unreviewed requests.

It was certainly not meant that way and I do apologize if it came across as such.

Maybe my impression about what is achieved or not is wrong.
From the (now closed) pull requests it did not become apparent whether you had actually reviewed them (as there was no comment on them up until now).

Is it wrong to suggest to seek more maintainers/helpers **if** you do not have the time (non-answered, open pull requests that are a few years old are usually an indicator for that)? If I was under a wrong impression, you are of course free to tell me that. But it is no reason to feel offended.

So, all is well and good luck with the project! :)

**Comment by haampie** [comment]
Hi @plougher, thanks for all your work on this project, it's highly appreciated! Also I don't think there is an issue with having certain pull requests open.

It's just that I'd prefer to work with a tagged version of software (or rather, package managers do), and at the same time I need commits that are on `master` but not in version 4.4 to make this project actually build from sources. There's three pull requests that have been merged between 6 and 13 months ago that did not end up in a tagged version yet; may I suggest to tag them as 4.5 or 4.4.1 such that more people feel comfortable actually using them?

**Comment by plougher** [comment]
> Hi @plougher, thanks for all your work on this project, it's highly appreciated! Also I don't think there is an issue with having certain pull requests open.
> 
> It's just that I'd prefer to work with a tagged version of software (or rather, package managers do), and at the same time I need commits that are on `master` but not in version 4.4 to make this project actually build from sources. There's three pull requests that have been merged between 6 and 13 months ago that did not end up in a tagged version yet; may I suggest to tag them as 4.5 or 4.4.1 such that more people feel comfortable actually using them?

I understand you'd like a tag to pull from.  My problem is I don't want that tag to look like a release - because Squashfs releases have always been fairly involved, with testing, updated documentation, etc. and this won't have any of that.

So I have created a tag "4.4-git.1" which should hopefully be want you want, without looking like a full release.

**Comment by haampie** [comment]
Thanks! For what it's worth, you can mark this `4.4-git.1` tag as a pre-release on github
